# Generated by Django 6.1.1 on 2026-09-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='notice_period',
            field=models.CharField(default='30 Days', max_length=1000),
            preserve_default=False,
        ),
    ]
