# Generated by Django 6.1.1 on 2026-09-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_notice_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='notice_period',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
